export const PLATFORMS = {
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    shortName: 'X',
    maxLength: 280,
    optimalLength: 220,
    hashtagLimit: 2,
    color: '#000000',
    bgColor: 'bg-black',
    textColor: 'text-white',
    icon: 'twitter',
    features: ['Threads support', 'Hashtag optimization', 'Engagement hooks'],
    contentFormats: ['Single tweet', 'Thread (3–20 tweets)', 'Quote tweet', 'Poll'],
    algorithmTips: [
      'Hook in the first 10 words — people skim fast',
      'Threads get 3–5× more reach than single tweets',
      'Reply to your own thread to keep it alive',
      'Post consistently — the algo rewards daily activity',
      'Questions and hot takes drive reply volume',
    ],
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    shortName: 'Instagram',
    maxLength: 2200,
    optimalLength: 150,
    hashtagLimit: 30,
    color: '#E4405F',
    bgColor: 'bg-gradient-to-br from-purple-600 via-pink-500 to-orange-400',
    textColor: 'text-white',
    icon: 'instagram',
    features: ['Caption optimization', 'Hashtag strategy', 'Call-to-action'],
    contentFormats: ['Single photo', 'Carousel (2–10 slides)', 'Reel (≤90 sec)', 'Story', 'Guide'],
    algorithmTips: [
      'First 125 characters show before "more" — make them punch',
      'Reels get 2–3× more reach than static posts right now',
      'Carousels keep people swiping = longer dwell time = more reach',
      'Put hashtags in the caption, not the first comment, for discovery',
      'A strong CTA ("save this", "tag a friend") boosts saves and shares',
    ],
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    shortName: 'Facebook',
    maxLength: 63206,
    optimalLength: 400,
    hashtagLimit: 3,
    color: '#1877F2',
    bgColor: 'bg-[#1877F2]',
    textColor: 'text-white',
    icon: 'facebook',
    features: ['Link previews', 'Engagement optimization', 'Audience targeting'],
    contentFormats: ['Text post', 'Photo post', 'Video', 'Link share', 'Event', 'Group post'],
    algorithmTips: [
      'Emotional content (joy, surprise, awe) gets shared the most',
      'Native video outperforms YouTube links — upload directly',
      'Ask questions to drive comment volume — comments > likes',
      'Long-form storytelling works well — Facebook readers have more patience',
      'Avoid "engagement bait" phrases like "like if you agree"',
    ],
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    shortName: 'LinkedIn',
    maxLength: 3000,
    optimalLength: 1200,
    hashtagLimit: 5,
    color: '#0A66C2',
    bgColor: 'bg-[#0A66C2]',
    textColor: 'text-white',
    icon: 'linkedin',
    features: ['Professional tone', 'Industry hashtags', 'Thought leadership'],
    contentFormats: ['Text post', 'Document/Carousel', 'Newsletter article', 'Poll', 'Video'],
    algorithmTips: [
      'First 3 lines appear before "see more" — hook hard and fast',
      'No links in the body — paste them in the first comment',
      'Personal stories outperform company news by 3–5×',
      'Line breaks every 1–2 sentences keep people reading',
      'Comment on your own post within the first hour to boost velocity',
    ],
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    shortName: 'TikTok',
    maxLength: 2200,
    optimalLength: 150,
    hashtagLimit: 5,
    color: '#000000',
    bgColor: 'bg-black',
    textColor: 'text-white',
    icon: 'tiktok',
    features: ['Video script hooks', 'Trending sounds strategy', 'For You Page optimization'],
    contentFormats: ['Short video (≤60 sec)', 'Long video (1–10 min)', 'TikTok LIVE', 'Duet', 'Stitch'],
    algorithmTips: [
      'Hook in the first 1–3 seconds or you lose the viewer forever',
      'On-screen text captions keep people watching longer — completion rate is king',
      'Use trending sounds — the algo amplifies content using popular audio',
      'Reply to comments with a video to create conversation chains',
      'Post 1–4× per day; consistency signals to the FYP algorithm',
    ],
  },
  gmail: {
    id: 'gmail',
    name: 'Gmail',
    shortName: 'Gmail',
    maxLength: 50000,
    optimalLength: 1500,
    hashtagLimit: 0,
    color: '#EA4335',
    bgColor: 'bg-[#EA4335]',
    textColor: 'text-white',
    icon: 'gmail',
    features: ['One-to-one outreach', 'Personalized templates', 'Subject line optimization'],
    contentFormats: ['Cold outreach', 'Follow-up', 'Newsletter', 'Reply draft', 'Internal email'],
    algorithmTips: [
      'Subject lines under 50 characters get the highest open rates',
      'Personalization tokens beyond {first_name} drive 2–3× reply rates',
      'Send between Tuesday and Thursday, 8–10 AM in the recipient timezone',
      'A clear single CTA outperforms multiple asks — one ask, one yes',
      'Reply chains improve deliverability — keep threads going where it makes sense',
    ],
  },
  outlook: {
    id: 'outlook',
    name: 'Outlook',
    shortName: 'Outlook',
    maxLength: 50000,
    optimalLength: 1500,
    hashtagLimit: 0,
    color: '#0078D4',
    bgColor: 'bg-[#0078D4]',
    textColor: 'text-white',
    icon: 'outlook',
    features: ['Enterprise outreach', 'Calendar integration', 'Microsoft 365 native'],
    contentFormats: ['Business email', 'Meeting invite', 'Status update', 'Proposal', 'Internal memo'],
    algorithmTips: [
      'Outlook senders see open data via read receipts — use them sparingly',
      'Microsoft 365 spam filters favor authenticated domains — set up SPF + DKIM',
      'Long-form professional content performs better than salesy copy',
      'Calendar links inside emails dramatically increase meeting conversion',
      'Subject prefixes like [Action] or [FYI] help recipients triage faster',
    ],
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest',
    shortName: 'Pinterest',
    maxLength: 500,
    optimalLength: 200,
    hashtagLimit: 20,
    color: '#E60023',
    bgColor: 'bg-[#E60023]',
    textColor: 'text-white',
    icon: 'pinterest',
    features: ['Pin descriptions', 'Board strategy', 'SEO-driven discovery'],
    contentFormats: ['Standard Pin', 'Idea Pin', 'Video Pin', 'Product Pin', 'Carousel Pin'],
    algorithmTips: [
      'Pinterest is a search engine — SEO-optimized descriptions rank for months',
      'Vertical images (2:3 ratio) take up more feed space and get more saves',
      'Keywords in the first 50 characters matter most for search ranking',
      'Idea Pins get 9× more comments than standard pins',
      'Pin consistently — 10–25 pins per day outperforms sporadic bursts',
    ],
  },
  snapchat: {
    id: 'snapchat',
    name: 'Snapchat',
    shortName: 'Snap',
    maxLength: 250,
    optimalLength: 80,
    hashtagLimit: 0,
    color: '#FFFC00',
    bgColor: 'bg-[#FFFC00]',
    textColor: 'text-black',
    icon: 'snapchat',
    features: ['Story scripts', 'Spotlight hooks', 'AR lens briefs'],
    contentFormats: ['Story', 'Spotlight video', 'Snap Map content', 'AR Lens promo', 'Snap Ad'],
    algorithmTips: [
      'Spotlight rewards completion rate — hook in the first second',
      'Vertical 9:16 is mandatory — landscape content gets cropped',
      'Music and text overlays increase Spotlight distribution',
      'Stories disappear in 24h — create urgency with exclusive content',
      'Consistency matters less than virality — one hit can drive millions of views',
    ],
  },
} as const

export type PlatformId = keyof typeof PLATFORMS
export type SocialPlatformId = 'twitter' | 'instagram' | 'linkedin' | 'facebook' | 'tiktok' | 'pinterest' | 'snapchat'
export type EmailPlatformId = 'gmail' | 'outlook'

export const SOCIAL_PLATFORM_IDS: SocialPlatformId[] = [
  'twitter',
  'instagram',
  'linkedin',
  'facebook',
  'tiktok',
  'pinterest',
  'snapchat',
]
export const EMAIL_PLATFORM_IDS: EmailPlatformId[] = ['gmail', 'outlook']

export const TONES = [
  { id: 'professional', name: 'Professional', description: 'Polished and business-appropriate' },
  { id: 'casual', name: 'Casual', description: 'Friendly and conversational' },
  { id: 'witty', name: 'Witty', description: 'Clever and entertaining' },
  { id: 'inspirational', name: 'Inspirational', description: 'Motivating and uplifting' },
  { id: 'educational', name: 'Educational', description: 'Informative and helpful' },
  { id: 'bold', name: 'Bold', description: 'Confident and direct — no hedging' },
  { id: 'storytelling', name: 'Storytelling', description: 'Narrative-driven and personal' },
] as const

export type ToneId = typeof TONES[number]['id']

export const CONTENT_TYPES = [
  { id: 'promotional', name: 'Promotional', description: 'Showcase products or services' },
  { id: 'educational', name: 'Educational', description: 'Share knowledge and tips' },
  { id: 'entertaining', name: 'Entertaining', description: 'Engage and amuse your audience' },
  { id: 'personal', name: 'Personal', description: 'Share stories and experiences' },
  { id: 'announcement', name: 'Announcement', description: 'Share news and updates' },
  { id: 'thought-leadership', name: 'Thought Leadership', description: 'Industry expertise and insights' },
  { id: 'engagement', name: 'Engagement', description: 'Questions, polls, conversation starters' },
] as const

export type ContentTypeId = typeof CONTENT_TYPES[number]['id']

export const THREAD_TWEET_COUNTS = [3, 5, 7, 9, 12] as const

export type ThreadTweetCount = typeof THREAD_TWEET_COUNTS[number]
